services:
  redis:
    image: redis:alpine
    restart: always

  weather:
    image: ghcr.io/arbaradoz976/weather-pyapp:latest
    build: .
    depends_on:
      - redis
    restart: always
    ports:
      - "8080:80"